version: "3"

services:
  dev-app:
    build:
      context: .
      args:
        NODE_ENV: development
    container_name: dev-node-app
    ports:
      - ${PORTA}:${PORTA}
    volumes:
      - .:/home/app
      - ./node_modules:/home/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - mongo-compose-network
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
      - nginx
    command: pnpm run dev

  db:
    image: mongo:latest
    container_name: mongo-dev-server
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - mongo-compose-network
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    container_name: redis-dev-server
    networks:
      - mongo-compose-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-dev-server
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge

volumes:
  mongo-db:
